version: 2
project_name: basis-data-ltt

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

archives:
  - files:
      - README.md

dockers_v2:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/basis-data-ltt:{{ .Tag }}"
    dockerfile: Dockerfile.release

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ index (split .Env.GITHUB_REPOSITORY \"/\") 1 }}"
