// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Arie Brainware",
            "email": "support@ariebrainware.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/disease": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Get a paginated list of diseases",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disease"
                ],
                "summary": "List all diseases",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Diseases retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Disease"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Add a new disease to the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disease"
                ],
                "summary": "Create a new disease",
                "parameters": [
                    {
                        "description": "Disease information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.createDiseaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Disease created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Disease"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/disease/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Get detailed information about a specific disease",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disease"
                ],
                "summary": "Get disease information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Disease ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Disease retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Disease"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Disease not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Soft delete a disease by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disease"
                ],
                "summary": "Delete a disease",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Disease ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Disease deleted",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Disease not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Update an existing disease's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disease"
                ],
                "summary": "Update disease information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Disease ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated disease information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.createDiseaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Disease updated",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Disease"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request or disease not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Authenticate user with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/endpoint.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Invalidate the user session token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User logout",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/patient": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Get a paginated list of patients with optional filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "List all patients",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search keyword for patient name, code, address, or phone",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by date range (last_2_days, last_3_months, last_6_months)",
                        "name": "group_by_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patients retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Register a new patient (public endpoint - no authentication required)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Create a new patient",
                "parameters": [
                    {
                        "description": "Patient information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.createPatientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patient created",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or patient already exists",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/patient/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Get detailed information about a specific patient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Get patient information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patient retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Patient"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Patient not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Soft delete a patient by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Delete a patient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patient deleted",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Patient not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Update an existing patient's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Update patient information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated patient information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Patient"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Patient updated",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Patient"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request or patient not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/signup": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User signup",
                "parameters": [
                    {
                        "description": "Signup details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Signup successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request or email already exists",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/therapist": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Get a paginated list of therapists with optional filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Therapist"
                ],
                "summary": "List all therapists",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search keyword for therapist name or NIK",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by date range (last_2_days, last_3_months, last_6_months)",
                        "name": "group_by_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Therapist retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Register a new therapist in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Therapist"
                ],
                "summary": "Create a new therapist",
                "parameters": [
                    {
                        "description": "Therapist information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.createTherapistRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Therapist created",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or therapist already exists",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/therapist/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Get detailed information about a specific therapist",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Therapist"
                ],
                "summary": "Get therapist information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Therapist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Therapist retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Therapist"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Therapist not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Approve a therapist account for system access",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Therapist"
                ],
                "summary": "Approve a therapist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Therapist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Therapist approval data (is_approved must be true)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Therapist"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Therapist updated",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or approval error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Soft delete a therapist by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Therapist"
                ],
                "summary": "Delete a therapist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Therapist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Therapist deleted",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Therapist not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Update an existing therapist's information (excluding approval status)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Therapist"
                ],
                "summary": "Update therapist information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Therapist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated therapist information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Therapist"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Therapist updated",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or therapist not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/token/validate": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Validate if the session token is valid and not expired",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Validate session token",
                "responses": {
                    "200": {
                        "description": "Valid session token",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or expired session token",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/treatment": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Get a paginated list of treatments with optional filtering by therapist, keyword, and date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Treatment"
                ],
                "summary": "List all treatments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by therapist ID",
                        "name": "therapist_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search keyword for patient name or patient code",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by specific date (YYYY-MM-DD format)",
                        "name": "group_by_date",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by logged-in therapist",
                        "name": "filter_by_therapist",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Treatments fetched successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request or session error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Add a new treatment record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Treatment"
                ],
                "summary": "Create a new treatment",
                "parameters": [
                    {
                        "description": "Treatment information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TreatementRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Treatment created successfully",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or duplicate treatment",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        },
        "/treatment/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Soft delete a treatment record by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Treatment"
                ],
                "summary": "Delete a treatment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Treatment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Treatment deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Treatment not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Update an existing treatment record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Treatment"
                ],
                "summary": "Update treatment information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Treatment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated treatment information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Treatment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Treatment updated successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Treatment"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request or treatment not found",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/util.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "endpoint.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "endpoint.LoginResponse": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string",
                    "example": "Admin"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "endpoint.SignupRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "endpoint.createDiseaseRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "A metabolic disease"
                },
                "name": {
                    "type": "string",
                    "example": "Diabetes"
                }
            }
        },
        "endpoint.createPatientRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "123 Main St"
                },
                "age": {
                    "type": "integer",
                    "example": 30
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "full_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "gender": {
                    "type": "string",
                    "example": "Male"
                },
                "health_history": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Diabetes",
                        "Hypertension"
                    ]
                },
                "job": {
                    "type": "string",
                    "example": "Engineer"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "patient_code": {
                    "type": "string",
                    "example": "J001"
                },
                "phone_number": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "081234567890",
                        "081234567891"
                    ]
                },
                "surgery_history": {
                    "type": "string",
                    "example": "Appendectomy 2020"
                }
            }
        },
        "endpoint.createTherapistRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "123 Main St"
                },
                "date_of_birth": {
                    "type": "string",
                    "example": "1980-01-01"
                },
                "email": {
                    "type": "string",
                    "example": "dr.john@example.com"
                },
                "full_name": {
                    "type": "string",
                    "example": "Dr. John Smith"
                },
                "height": {
                    "type": "integer",
                    "example": 175
                },
                "is_approved": {
                    "type": "boolean",
                    "example": false
                },
                "nik": {
                    "type": "string",
                    "example": "1234567890123456"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "phone_number": {
                    "type": "string",
                    "example": "081234567890"
                },
                "role": {
                    "type": "string",
                    "example": "Physical Therapist"
                },
                "weight": {
                    "type": "integer",
                    "example": 70
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "model.Disease": {
            "description": "Disease information",
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string",
                    "example": "A metabolic disease"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Diabetes"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Patient": {
            "description": "Patient information",
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "123 Main St"
                },
                "age": {
                    "type": "integer",
                    "example": 30
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "full_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "gender": {
                    "type": "string",
                    "example": "Male"
                },
                "health_history": {
                    "type": "string",
                    "example": "Diabetes,Hypertension"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "job": {
                    "type": "string",
                    "example": "Engineer"
                },
                "password": {
                    "type": "string",
                    "example": "hashed_password"
                },
                "patient_code": {
                    "type": "string",
                    "example": "J001"
                },
                "phone_number": {
                    "type": "string",
                    "example": "081234567890"
                },
                "surgery_history": {
                    "type": "string",
                    "example": "Appendectomy 2020"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Therapist": {
            "description": "Therapist information",
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "123 Main St"
                },
                "createdAt": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string",
                    "example": "1980-01-01"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string",
                    "example": "dr.john@example.com"
                },
                "full_name": {
                    "type": "string",
                    "example": "Dr. John Smith"
                },
                "height": {
                    "type": "integer",
                    "example": 175
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_approved": {
                    "type": "boolean",
                    "example": false
                },
                "nik": {
                    "type": "string",
                    "example": "1234567890123456"
                },
                "password": {
                    "type": "string",
                    "example": "hashed_password"
                },
                "phone_number": {
                    "type": "string",
                    "example": "081234567890"
                },
                "role": {
                    "type": "string",
                    "example": "Physical Therapist"
                },
                "updatedAt": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer",
                    "example": 70
                }
            }
        },
        "model.TreatementRequest": {
            "description": "Treatment request information",
            "type": "object",
            "properties": {
                "issues": {
                    "type": "string",
                    "example": "Back pain"
                },
                "next_visit": {
                    "type": "string",
                    "example": "2025-01-22"
                },
                "patient_code": {
                    "type": "string",
                    "example": "J001"
                },
                "remarks": {
                    "type": "string",
                    "example": "Patient showed improvement"
                },
                "therapist_id": {
                    "type": "integer",
                    "example": 1
                },
                "treatment": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Massage therapy",
                        "Exercise"
                    ]
                },
                "treatment_date": {
                    "type": "string",
                    "example": "2025-01-15"
                }
            }
        },
        "model.Treatment": {
            "description": "Treatment information",
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "issues": {
                    "type": "string",
                    "example": "Back pain"
                },
                "next_visit": {
                    "type": "string",
                    "example": "2025-01-22"
                },
                "patient_code": {
                    "type": "string",
                    "example": "J001"
                },
                "remarks": {
                    "type": "string",
                    "example": "Patient showed improvement"
                },
                "therapist_id": {
                    "type": "integer",
                    "example": 1
                },
                "treatment": {
                    "type": "string",
                    "example": "Massage therapy,Exercise"
                },
                "treatment_date": {
                    "type": "string",
                    "example": "2025-01-15"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "util.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "SessionToken": {
            "description": "Session token for authenticated requests",
            "type": "apiKey",
            "name": "session-token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:19091",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "LTT Backend API",
	Description:      "REST API for managing patient data, treatments, and therapy sessions\nThis API provides endpoints for patient management, disease tracking, treatment records, and therapist management.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
